# Test Podfile WITHOUT Firebase (leveldb isolation)
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'
prepare_react_native_project!

# Temporarily disabled Firebase to isolate leveldb build issues
# use_frameworks! :linkage => :static
# $RNFirebaseAsStaticFramework = true

target 'TempGlicoTrack' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Simplified post_install without Firebase/LevelDB patches
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Ensure consistent deployment target for all pods (Hermes compatible)
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        
        # Disable bitcode (deprecated in Xcode 14+)
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        
        # Basic React Native New Architecture support
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_NEW_ARCH_ENABLED=1'
      end
    end
    
    # LevelDB patches removed - testing build without Firebase
  end
end
