name: iOS Build - Incremental

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ios:
    name: Pod Install + Xcode Build Test
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Environment Info
      run: |
        echo "=== Environment ==="
        xcodebuild -version
        echo "Node: $(node --version)"
        echo "Ruby: $(ruby --version)"
        echo "CocoaPods: $(pod --version)"

    - name: Pod Install (Known Working Step)
      run: |
        cd ios
        echo "=== Testing Pod Install ==="
        pod install --verbose
      env:
        RCT_NEW_ARCH_ENABLED: 1
        USE_HERMES: 1

    - name: Verify Workspace Creation
      run: |
        cd ios
        echo "=== Verifying Workspace ==="
        if [ -f "GlicoTrack.xcworkspace/contents.xcworkspacedata" ]; then
          echo "✅ Workspace created successfully"
          ls -la GlicoTrack.xcworkspace/
        else
          echo "❌ Workspace not found"
          exit 1
        fi

    - name: Xcode Build (New Step - Testing)"
      run: |
        cd ios
        echo "=== Building iOS App ==="
        xcodebuild \
          -workspace GlicoTrack.xcworkspace \
          -scheme GlicoTrack \
          -configuration Debug \
          -sdk iphonesimulator \
          -derivedDataPath build \
          CODE_SIGNING_ALLOWED=NO \
          build

    - name: Upload App (If Build Succeeds)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: GlicoTrack-iOS-Incremental
        path: ios/build/Build/Products/Debug-iphonesimulator/TempGlicoTrack.app